### ISSUE TITLE
abismal.cpp:42:10: fatal error: 'omp.h' file not found

### ISSUE THREAD

**Issue by SCYangcode** [smithlabcode/abismal#17] opened 2022-12-23 08:55 UTC
Hello,
when I using `make` or `make install` command to install abysmal, it shows error like this: "abismal.cpp:42:10: fatal error: 'omp.h' file not found ". Please someone tell me how should I cope with it?

**Comment by guilhermesena1** [comment] 2022-12-27 15:47
Hello,

It's possible you may not have OpenMP installed, which abismal uses to map reads in parallel. Can you let us know which operating system you are trying to install it at? For instance on Ubuntu you can install openmp with

```
sudo apt install libomp-dev
```

And on Mac OSX (with homebrew) with
```
brew install libomp
```

**Comment by yl139840** [comment] 2022-12-30 05:30
Hi, Guilherme
Thanks for the reply, my operating system is Mac OSX. I guess this is why the problem pop out.

Best,
Songchen Yang

2022年12月27日 23:47，Guilherme Sena ***@***.******@***.***>> 写道：



Hello,

It's possible you may not have OpenMP installed, which abismal uses to map reads in parallel. Can you let us know which operating system you are trying to install it at? For instance on Ubuntu you can install openmp with

sudo apt install libomp-dev


And on Mac OSX (with homebrew) with

brew install libomp

**Comment by andrewdavidsmith** [comment] 2023-08-03 20:31
@SCYangcode The issue is most likely that you would need to be using gcc or the llvm clang for the compiler on macos. The "gcc" and "clang" that seems to exist on macos is actually something different, and since the most recent update, I can't make it work on macos. So I need to install gcc through homebrew and then try to use that compiler. But it's not convenient. When I don't use a real gcc, I have a very hard time making things work. Hopefully this will improve in the near future.

**Comment by andrewdavidsmith** [comment] 2023-08-03 20:33
I'm going to close this issue, and I'll try to update instructions for macos build soon.

**Closed by andrewdavidsmith** 2023-08-03 20:33 UTC
